# FriendlyChat

use_frameworks!
platform :ios, '8.0'
pod 'Firebase/Storage'
pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'Firebase/RemoteConfig'
pod 'FirebaseUI'
pod 'FirebaseAuth'
pod 'Firebase/DynamicLinks'
pod 'GoogleSignIn'
pod 'MessageKit'
target 'FriendlyChatSwift' do
end


